/**
 * Generate src/lib/data/catalog.ts from Supabase (real DB).
 * Keeps shape compatible with src/lib/mocks/catalog.ts so storefront
 * components don't need to change.
 *
 *   npm run data:refresh   (manual)
 *   npm run build          (pre-build hook)
 */
import { config } from "dotenv";
config({ path: ".env.local" });
config({ path: ".env" });
import ws from "ws";
import { createClient } from "@supabase/supabase-js";
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

(globalThis as any).WebSocket ??= ws;

const URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const KEY = process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
if (!URL || !KEY) {
  console.warn("[generate-catalog] No Supabase creds — skipping (will keep existing data file)");
  process.exit(0);
}
const supabase = createClient(URL, KEY, { auth: { persistSession: false } });

const COLOR_HEX: Record<string, string> = {
  preto: "#0F172A", branco: "#FFFFFF", azul: "#3B82F6", cyan: "#22D3EE",
  vermelho: "#EF4444", verde: "#10B981", amarelo: "#F59E0B", cinza: "#64748B",
  bege: "#D6CFC2", prata: "#CBD5E1", laranja: "#F97316", "azul/cyan": "#22D3EE",
  "preto/azul": "#1E40AF", "branco/preto": "#0F172A", "preto/verde": "#10B981",
  "verde militar": "#3F5235", "azul espelhado": "#1E3A8A", "amarelo neon": "#FACC15",
  padrão: "#94A3B8",
};
const colorHex = (name: string) => COLOR_HEX[name.toLowerCase()] ?? "#94A3B8";

async function main() {
  const { data: cats, error: ce } = await supabase
    .from("categories")
    .select("id, slug, name, image_url, banner_url, position")
    .order("position");
  if (ce) throw ce;

  const { data: products, error: pe } = await supabase
    .from("products")
    .select(
      `id, slug, title, description, brand, base_price, sale_price, sales_count, rating_avg, rating_count,
       category:categories(slug),
       product_images(url, alt, position),
       product_variants(size, color, stock)`,
    )
    .eq("status", "active")
    .order("created_at", { ascending: false });
  if (pe) throw pe;

  const categories = (cats ?? []).map((c, i) => {
    const count = (products ?? []).filter((p: any) => p.category?.slug === c.slug).length;
    return {
      id: c.id,
      slug: c.slug,
      name: c.name,
      description: c.name,
      imageUrl: c.image_url ?? "",
      productCount: count || 0,
    };
  });

  const prods = (products ?? []).map((p: any, idx: number) => {
    const images: string[] = (p.product_images ?? [])
      .sort((a: any, b: any) => a.position - b.position)
      .map((i: any) => i.url);
    while (images.length < 3) images.push(images[0] ?? "");
    const sizes = Array.from(new Set((p.product_variants ?? []).map((v: any) => v.size))).filter(Boolean);
    const colorNames = Array.from(new Set((p.product_variants ?? []).map((v: any) => v.color))).filter(Boolean);
    const colors = colorNames.map((name) => ({ name: name as string, hex: colorHex(name as string) }));
    const stock = (p.product_variants ?? []).reduce((s: number, v: any) => s + (v.stock ?? 0), 0);
    let badge: string | undefined;
    if (p.sale_price && p.base_price) {
      const off = Math.round((1 - p.sale_price / p.base_price) * 100);
      if (off >= 10) badge = `-${off}%`;
    }
    if (!badge && idx < 3) badge = "HOT";
    return {
      id: p.id,
      slug: p.slug,
      title: p.title,
      brand: p.brand ?? "NEX",
      category: p.category?.slug ?? "nex-style",
      priceCents: p.base_price,
      salePriceCents: p.sale_price ?? undefined,
      images,
      rating: Number(p.rating_avg ?? 4.7),
      reviewCount: p.rating_count ?? Math.floor(Math.random() * 400) + 20,
      badge,
      sizes,
      colors,
      description: p.description ?? "",
      stock,
    };
  });

  const partners = [
    "NIKE","ADIDAS","PUMA","ASICS","NEW BALANCE","UNDER ARMOUR","MIZUNO","WILSON",
  ].map((name) => ({ name, logoUrl: "" }));

  const out = `// AUTO-GENERATED by scripts/generate-catalog.ts — do not edit by hand
// Run: npm run data:refresh
import type { Category, Product, Partner } from "@/lib/mocks/types";

export const categories: Category[] = ${JSON.stringify(categories, null, 2)};

export const products: Product[] = ${JSON.stringify(prods, null, 2)};

export const partners: Partner[] = ${JSON.stringify(partners, null, 2)};

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.category === categorySlug);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getFeatured(): Product[] {
  return products.filter((p) => p.salePriceCents).slice(0, 8);
}

export function getBestSellers(): Product[] {
  return [...products].sort(() => 0).slice(0, 6);
}

export function getWeeklyFinds(): Product[] {
  return products.slice(0, 6);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.title.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q),
  );
}
`;

  mkdirSync("src/lib/data", { recursive: true });
  writeFileSync(join("src/lib/data/catalog.ts"), out);
  console.log(`✓ wrote src/lib/data/catalog.ts — ${categories.length} categorias, ${prods.length} produtos`);
}

main().catch((e) => {
  console.error("✗", e);
  process.exit(1);
});
