// AUTO-GENERATED by scripts/generate-catalog.ts — do not edit by hand
// Run: npm run data:refresh
import type { Category, Product, Partner } from "@/lib/mocks/types";

export const categories: Category[] = [
  {
    "id": "dffd2dc0-70c5-4b48-ae27-7b8022b08426",
    "slug": "nex-fut",
    "name": "NEX FUT",
    "description": "NEX FUT",
    "imageUrl": "https://images.unsplash.com/photo-1551958219-acbc608c6377?w=600&q=80",
    "productCount": 3
  },
  {
    "id": "3ab34661-e83e-4022-9551-d1b5c335b9a8",
    "slug": "nex-fit",
    "name": "NEX FIT",
    "description": "NEX FIT",
    "imageUrl": "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&q=80",
    "productCount": 3
  },
  {
    "id": "1cb9ff2d-a92b-479a-acb7-9f201a1b194e",
    "slug": "nex-beach",
    "name": "NEX BEACH",
    "description": "NEX BEACH",
    "imageUrl": "https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600&q=80",
    "productCount": 3
  },
  {
    "id": "f02dd229-4251-4c14-8bc6-e9884f700d60",
    "slug": "nex-padel",
    "name": "NEX PADEL",
    "description": "NEX PADEL",
    "imageUrl": "https://images.unsplash.com/photo-1511067007398-7e4b90cfa4bc?w=600&q=80",
    "productCount": 3
  },
  {
    "id": "3ebfc3b6-97fb-4203-821e-269c896b96e5",
    "slug": "nex-run",
    "name": "NEX RUN",
    "description": "NEX RUN",
    "imageUrl": "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=80",
    "productCount": 3
  },
  {
    "id": "e4b71a08-55d2-4c03-a17d-af2f37312f33",
    "slug": "nex-court",
    "name": "NEX COURT",
    "description": "NEX COURT",
    "imageUrl": "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600&q=80",
    "productCount": 3
  },
  {
    "id": "e66d200a-0e40-4304-837b-ed125e454abd",
    "slug": "nex-style",
    "name": "NEX STYLE",
    "description": "NEX STYLE",
    "imageUrl": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80",
    "productCount": 3
  },
  {
    "id": "10b00459-920e-4be1-b0de-96fa2c780d98",
    "slug": "nex-tech",
    "name": "NEX TECH",
    "description": "NEX TECH",
    "imageUrl": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    "productCount": 3
  }
];

export const products: Product[] = [
  {
    "id": "00000000-0000-4000-8000-000000000001",
    "slug": "produto-teste-padel",
    "title": "Produto Teste",
    "brand": "NEX",
    "category": "nex-padel",
    "priceCents": 9900,
    "images": [
      "/no-image.svg",
      "/no-image.svg",
      "/no-image.svg"
    ],
    "rating": 0,
    "reviewCount": 0,
    "sizes": ["Único"],
    "colors": [{ "name": "Padrão", "hex": "#334155" }],
    "description": "Produto de teste para visualização.",
    "stock": 10
  },
  {
    "id": "00000000-0000-4000-8000-000000000002",
    "slug": "produto-teste-beach",
    "title": "Produto Teste",
    "brand": "NEX",
    "category": "nex-beach",
    "priceCents": 9900,
    "images": [
      "/no-image.svg",
      "/no-image.svg",
      "/no-image.svg"
    ],
    "rating": 0,
    "reviewCount": 0,
    "sizes": ["Único"],
    "colors": [{ "name": "Padrão", "hex": "#334155" }],
    "description": "Produto de teste para visualização.",
    "stock": 10
  },
  {
    "id": "00000000-0000-4000-8000-000000000003",
    "slug": "produto-teste-run",
    "title": "Produto Teste",
    "brand": "NEX",
    "category": "nex-run",
    "priceCents": 9900,
    "images": [
      "/no-image.svg",
      "/no-image.svg",
      "/no-image.svg"
    ],
    "rating": 0,
    "reviewCount": 0,
    "sizes": ["Único"],
    "colors": [{ "name": "Padrão", "hex": "#334155" }],
    "description": "Produto de teste para visualização.",
    "stock": 10
  },
  {
    "id": "00000000-0000-4000-8000-000000000004",
    "slug": "produto-teste-court",
    "title": "Produto Teste",
    "brand": "NEX",
    "category": "nex-court",
    "priceCents": 9900,
    "images": [
      "/no-image.svg",
      "/no-image.svg",
      "/no-image.svg"
    ],
    "rating": 0,
    "reviewCount": 0,
    "sizes": ["Único"],
    "colors": [{ "name": "Padrão", "hex": "#334155" }],
    "description": "Produto de teste para visualização.",
    "stock": 10
  },
  {
    "id": "00000000-0000-4000-8000-000000000005",
    "slug": "produto-teste-fut",
    "title": "Produto Teste",
    "brand": "NEX",
    "category": "nex-fut",
    "priceCents": 9900,
    "images": [
      "/no-image.svg",
      "/no-image.svg",
      "/no-image.svg"
    ],
    "rating": 0,
    "reviewCount": 0,
    "sizes": ["Único"],
    "colors": [{ "name": "Padrão", "hex": "#334155" }],
    "description": "Produto de teste para visualização.",
    "stock": 10
  },
  {
    "id": "00000000-0000-4000-8000-000000000006",
    "slug": "produto-teste-fit",
    "title": "Produto Teste",
    "brand": "NEX",
    "category": "nex-fit",
    "priceCents": 9900,
    "images": [
      "/no-image.svg",
      "/no-image.svg",
      "/no-image.svg"
    ],
    "rating": 0,
    "reviewCount": 0,
    "sizes": ["Único"],
    "colors": [{ "name": "Padrão", "hex": "#334155" }],
    "description": "Produto de teste para visualização.",
    "stock": 10
  },
  {
    "id": "00000000-0000-4000-8000-000000000007",
    "slug": "produto-teste-style",
    "title": "Produto Teste",
    "brand": "NEX",
    "category": "nex-style",
    "priceCents": 9900,
    "images": [
      "/no-image.svg",
      "/no-image.svg",
      "/no-image.svg"
    ],
    "rating": 0,
    "reviewCount": 0,
    "sizes": ["Único"],
    "colors": [{ "name": "Padrão", "hex": "#334155" }],
    "description": "Produto de teste para visualização.",
    "stock": 10
  },
  {
    "id": "00000000-0000-4000-8000-000000000008",
    "slug": "produto-teste-tech",
    "title": "Produto Teste",
    "brand": "NEX",
    "category": "nex-tech",
    "priceCents": 9900,
    "images": [
      "/no-image.svg",
      "/no-image.svg",
      "/no-image.svg"
    ],
    "rating": 0,
    "reviewCount": 0,
    "sizes": ["Único"],
    "colors": [{ "name": "Padrão", "hex": "#334155" }],
    "description": "Produto de teste para visualização.",
    "stock": 10
  }
]

export const partners: Partner[] = [
  {
    "name": "NIKE",
    "logoUrl": ""
  },
  {
    "name": "ADIDAS",
    "logoUrl": ""
  },
  {
    "name": "PUMA",
    "logoUrl": ""
  },
  {
    "name": "ASICS",
    "logoUrl": ""
  },
  {
    "name": "NEW BALANCE",
    "logoUrl": ""
  },
  {
    "name": "UNDER ARMOUR",
    "logoUrl": ""
  },
  {
    "name": "MIZUNO",
    "logoUrl": ""
  },
  {
    "name": "WILSON",
    "logoUrl": ""
  }
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.category === categorySlug);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getFeatured(): Product[] {
  return products.filter((p) => p.salePriceCents).slice(0, 8);
}

export function getBestSellers(): Product[] {
  return products.slice(0, 4);
}

export function getWeeklyFinds(): Product[] {
  return products.slice(0, 6);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.title.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q),
  );
}
